name: 'Package CI'

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16.13.x
        cache: npm

    - name: Install and Test
      run:  |
          npm ci
          npm test
  eslint:
    runs-on: ubuntu-latest
    with: 
      eslint-config-path: "./.eslintrc"
    steps:
    - name: Check For esLint
      run:  npm run lint

  vulnerabilities:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: vulnerabilities test
      run:  npm audit --json
